# Generated by Django 5.2.4 on 2026-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_contactquery_alter_profile_id_alter_useractivity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
