# Generated by Django 5.2.4 on 2026-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0004_contactquery_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='social_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_shared', models.CharField(max_length=200)),
            ],
        ),
    ]
